name = "storiq"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "storiq-db"
database_id = "992fe55f-d182-4c36-9841-1e966af4a50b"
migrations_dir = "prisma/migrations"
migrations_pattern = "prisma/migrations/*/migration.sql"

[vars]
NEXT_PUBLIC_APP_NAME = "Storiq"
